version: '3'
services:
    gluedev:
        container_name: glue3.0
        image: vishalkc2/glue3.0:latest
        ports:
            - 8888:8888
            - 4040:4040
            - 8080:8080
            - 7077:7077
        restart: unless-stopped
        environment:
            ZEPPELIN_NOTEBOOK_DIR: 'opt/work/notebook'
            ZEPPELIN_LOG_DIR: 'opt/work/notebook/logs'
            AWS_PROFILE: 'default'
        volumes:
            - <.aws folder path>:/root/.aws
            - ./glue-jobs:/opt/work/glue-jobs
        entrypoint: /home/jupyter/jupyter_start.sh
networks:
    default:
        driver: bridge